// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main', []);
x$.controller('main', ['$scope', '$http', '$timeout'].concat(function($scope, $http, $timeout){
  var primaryName, pad, liquidHeight, color;
  primaryName = ["石門水庫", "新山水庫", "翡翠水庫", "寶山水庫", "寶山第二水庫", "永和山水庫", "明德水庫", "鯉魚潭水庫", "德基水庫", "石岡壩", "霧社水庫", "日月潭水庫", "仁義潭水庫", "蘭潭水庫", "烏山頭水庫", "曾文水庫", "南化水庫", "阿公店水庫", "阿公店水庫(洩洪至二仁溪)", "牡丹水庫", "成功水庫"];
  pad = function(v, len){
    var u;
    len == null && (len = 2);
    u = v + "";
    if (u.length < len) {
      return repeatString$(" ", len - u.length) + u;
    }
    return u;
  };
  liquidHeight = {
    side: d3.scale.linear().domain([0, 100]).range([260, 60]),
    bottom: d3.scale.linear().domain([0, 100]).range([290, 80]),
    top: d3.scale.linear().domain([0, 100]).range([230, 40])
  };
  color = d3.scale.linear().domain([0, 25, 50, 75, 100]).range(['#f03', '#f96', '#ff9', '#9fc', '#0ff']);
  $scope.loading = {
    exigency: true,
    primary: true,
    secondary: true
  };
  return $http({
    url: 'live.json',
    method: 'GET'
  }).success(function(data){
    var names, res$, k, dates, secondaryName, xAxis, yAxis, i$, len$, n, link, j$, i, d1, d2, p1, p2, nodata, volume, percent, idx, ref$, jdx, delta, remains, obj;
    res$ = [];
    for (k in data) {
      res$.push(k);
    }
    names = res$;
    dates = (function(){
      var results$ = [];
      for (k in data[names[0]]) {
        results$.push(k);
      }
      return results$;
    }()).sort();
    secondaryName = names.filter(function(it){
      return primaryName.indexOf(it) < 0;
    });
    xAxis = d3.scale.ordinal().domain(dates).range((function(){
      var i$, step$, results$ = [];
      for (i$ = 0, step$ = 765 / dates.length; step$ < 0 ? i$ >= 765 : i$ <= 765; i$ += step$) {
        results$.push(i$);
      }
      return results$;
    }()));
    yAxis = d3.scale.linear().domain([0, 100]).range([173, 7]);
    $scope.reservoirs = [];
    for (i$ = 0, len$ = names.length; i$ < len$; ++i$) {
      n = names[i$];
      link = [];
      for (j$ = dates.length - 2; j$ >= 0; --j$) {
        i = j$;
        d1 = dates[i];
        d2 = dates[i + 1];
        p1 = data[n][d1].p;
        p2 = data[n][d2].p;
        nodata = p1 === -1 || p2 === -1 ? true : false;
        if (!nodata) {
          link.push([xAxis(d1), xAxis(d2), yAxis(data[n][d1].p), yAxis(data[n][d2].p)]);
        }
      }
      volume = parseInt(data[n][dates[dates.length - 1]].v / 10) / 10;
      percent = parseInt((data[n][dates[dates.length - 1]].p * 10) / 10);
      idx = dates.length - 1;
      ref$ = [-1, -1], p1 = ref$[0], p2 = ref$[1];
      while (p1 === -1) {
        if (!data[n][dates[idx]]) {
          break;
        }
        p1 = data[n][dates[idx]].p;
        idx--;
      }
      jdx = idx - 7;
      while (p2 === -1) {
        if (!data[n][dates[jdx]]) {
          break;
        }
        p2 = data[n][dates[jdx]].p;
        jdx--;
      }
      delta = (p2 - p1) / (idx - jdx + 1);
      if (delta > 0) {
        remains = parseInt(p1 / 7 / delta);
      } else {
        remains = -1;
      }
      obj = {
        name: n,
        side: liquidHeight.side(data[n][dates[dates.length - 1]].p),
        bottom: liquidHeight.bottom(data[n][dates[dates.length - 1]].p),
        top: liquidHeight.top(data[n][dates[dates.length - 1]].p),
        color: color(data[n][dates[dates.length - 1]].p),
        link: link,
        volume: volume,
        percent: percent,
        start: dates[0],
        end: dates[dates.length - 1],
        remains: remains
      };
      $scope.reservoirs.push(obj);
    }
    $scope.exigency = $scope.reservoirs.filter(function(it){
      return primaryName.indexOf(it.name) >= 0 && it.remains <= 13 && it.remains >= 0;
    });
    $scope.loading.exigency = false;
    $timeout(function(){
      $scope.loading.primary = false;
      return $scope.primary = $scope.reservoirs.filter(function(it){
        return primaryName.indexOf(it.name) >= 0;
      });
    }, 1000);
    return $timeout(function(){
      $scope.loading.secondary = false;
      return $scope.secondary = $scope.reservoirs.filter(function(it){
        return primaryName.indexOf(it.name) < 0;
      });
    }, 3000);
  });
}));
function repeatString$(str, n){
  for (var r = ''; n > 0; (n >>= 1) && (str += str)) if (n & 1) r += str;
  return r;
}